### ISSUE TITLE
Making the package importable [Meteor]

### ISSUE THREAD

**Issue by peterchoo** [Semantic-Org/Semantic-UI-LESS#1]
Hi all,

I'm hoping to be able to use the LESS stuff in my application, and after a comment from @splendido on crater, I thought I'd have a quick look and see what I could get done.

[Here](https://github.com/peterchoo/Semantic-UI-LESS/tree/importable) is the initial set of changes I've made to the package to allow me to import it into a Meteor application.

The changes I made are fairly lightweight, but as far as I can see will not allow for external themes to be applied over the top, but it's a start!  Here are the steps I took:

1. `SemanticUI-LESS$ find . -type f -name "*.overrides" -exec mv "{}" "{}".import.less \;`
2. `SemanticUI-LESS$ find . -type f -name "*.variables" -exec mv "{}" "{}".import.less \;`
3. Create default theme.config file (I changed `themes/` to `themes`, and `site/` to `_site`, and `theme.less` to `theme.less.import.less`)
4. Change `theme.less to `theme.less.import.less` or `theme.import.less` (I used the former to follow the pattern I used on the overrides/variables files)
5. Update package.js to have `.import.less` on the files changed, and add `theme.config` to the addFiles array.

If you're not familiar with the less processor in Meteor, it will ignore files ending `.import.less`.

The package now processes all the remaining `.less` files in the order they are in the array provided to `api.addFiles()`.  This order may need changing to match the build order if some parts of the LESS depend on others.  My knowledge of LESS is rather shallow, and I've only really had a short look at the gulp build stuff.

A brief experiment has shown that I cannot set something like `@button: 'amazon';` and have it affect the build process inside the package.  My current plan is to find out if having the `Semantic-UI-LESS` package include *only* the default theme, and reference the main repository for any theme examples.  If that works (I can't see why not), then my next investigation will be into whether I can use and imply the main package in a theme package and add my LESS theme into that as a custom package... we shall see!

Anyhow, this is the start I've made, let me know what you think etc :)

**Comment by splendido** [comment]
Hello @peterchoo!

I think renaming everything to `.import.less` is a really good start! :)

I also think, which IMHO is the obvious use case, the `theme.config` and `theme.less` should be put into the app folder by the developer to select the theme she prefer.

I'd say we might try to understand wheter from inside these files we could import something like 

`packages/semantic_ui_css/something.import.less`

this is somehting like the path used to download the assets to the client side (lets check the path from where fonts are downloaded on the client).

If this is the case, it might be quite easy to write a couple of  templates for `theme.config` and `theme.less`.


Otherwise, the wiser approach so far I can know about is the one used by @nemo64 for his [nemo64:bootstrap](https://atmospherejs.com/nemo64/bootstrap) you can find on this [repo](https://github.com/Nemo64/meteor-bootstrap)

Perhaps @nemo64 would be willing to give us some help? :-)

**Comment by jlukic** [comment]
There are explicit locations for you to define your variables.
* If you're changing a theme, its `theme.config`.
* If you're modifying an element variable for your site its `site/elements/button.variables`
* If you're adding css overrides to an element its `site/elements/button.overrides`
* If you're creating a packaged theme its `themes/theme-name/elements.{variables,.overrides}`

Please [read the theming overview](http://learnsemantic.com/themes/overview.html) for more details.

**Comment by peterchoo** [comment]
@jlukic Thanks for the clarification, I wasn't aware of the variable scoping.  With the restrictions outlines above, it doesn't sound like including a Semantic UI LESS package in the manner I adjusted it above will give you anything other than the default LESS compiled into a CSS file. I had a feeling the order in which files were processed was important.

It seems to me that the best approach would be to do what @splendido suggested above, and look at @nemo64 's approach, creating some custom middleware to compile the LESS files in a way which would on it's own provide the same output as the css available in the `semantic:ui-css` library, but also add a compile time step to process the LESS files and intelligently insert the override/variable files from either a wrapper package, or the application the package is included in.

When I first looked into this, I was studying how @nemo64 did it with the bootstrap stuff, it's an area I'm not too familiar with in Meteor, so any help provided for that would be very much appreciated.

**Comment by splendido** [comment]
@peterchoo could you please make reference to the Meteor platform within the OP title?

**Comment by peterchoo** [comment]
@splendido Your last comment has removed some blinkers for me, in that I'm no longer so sure that appending `.import.less` to everything is such a good idea - What about the other ways of including this repository? Is this for Meteor only, or will this also exist on bower/npm? We could just leave the files as .overrides and .variables and manipulate them in the build process.

The best course of action now would be to write some middleware akin to @nemo64's bootstrap - having looked more into it, this would take a sub-package containing the data, has a configuration file for the list of all files within the package, and then for all these files gets the content, and saves it to one output file, which the application's inclusion of the `less` package consumes.  It also replaces any `@import` statement with the actual data from the file.

This sounds like an approach we can use, but it would need to be able to process the files in the way @jlukic outlined above.  We would also need to figure out how we can include external sources.  I'm wondering whether we can do this in one step, or whether the package can provide a set of files for a second build step?  

I have also been looking at the [Meteor LESS package compile process](https://github.com/meteor/meteor/blob/devel/packages/less/plugin/compile-less.js) and it takes advantage of Fibers/Futures.  I haven't had any experience using them myself, but I would assume that we could use them here so that we only generate the compiled LESS file for the applications less package to compile for us.  We could `api.imply('less')` in this package, or say "Do `meteor add semantic:ui less` to add both packages required to use the less theme".

This would give us a package which would on it's own create a less file using only the defaults.  If we get the compile process right, users could have a file in their project which acts as `theme.config` so that they could override themes for specific bits (no file = defaults for all) which would let them use any of the pre-defined themes in Semantic-UI already.

We could also provide a template package for adding custom themes, which would make all the theme files added available to the compile step.  How exactly we go about the compile step I don't know.  I think we will definitely have to use Futures, but with my inexperience I can't say how just yet.  My gut feeling is that we can create an in memory file cache, and when all files of config type have been processed, we can then go through the build process for all the files in `definitions/` and apply any theme files over the top.  I've excluded site stuff from this process, as we could just leave that to the user to override in in application .less files.

Your thoughts?

**Comment by jlukic** [comment]
The npm package includes a complete build script, I spent quite a bit of time working on it, and for me this is the preferred method of consuming the themable Semantic UI. You can read more about the original plan [in this thread](https://github.com/Semantic-Org/Semantic-UI/issues/1385#issue-51125575)

```
npm install semantic-ui
```

![Getting Started](https://dl.dropboxusercontent.com/u/2657007/install.gif)

I'm a bit unfamiliar with how `api.addFiles()` actually affects its use with Meteor. Are those files exposed somewhere? How does a developer choose which files to include on which page? Are you able to edit files in meteor packages?

**Comment by peterchoo** [comment]
Meteor itself has an automatic include process, i.e. if the less package is included in your application, every `.less` file in the folder structure (with the exception of anything in a package) will be processed.  This has a down-side as the order in which the files is evaluated is a bit complex.  There is logic behind it, but unless you know it exactly you cannot guarantee you've got it right.

Inside a Meteor package, however, the `api.addFiles()` function is what lets Meteor know which files are to be evaluated/executed by the application.  In a package you must explicitly say which files you add, and in which order.  The  `Package.onUse()` function is what is called when a package is evaluated by the Meteor.  This checks which packages (if any) the package relies on (as defined by `api.use()`) and which packages are implied (`api.imply()` means if you use this package, you use the implied packages as well).

Each time `api.addFiles()` is called, the file (or array of files) is evaluated, in that specific order.  You can optionally pass a second parameter to define where the files should be evaluated, `server`, `client`, `web.browser` and `web.cordova`.

With all that said, the files are not exposed anywhere, and you cannot edit them.  That's why in my comment above I suggest that once we find a middleware solution which would work, we have a sample package for applying a theme on top using that same middleware.

**Comment by jlukic** [comment]
Anyone willing to fork the readme and write a short explanatory note slash call for help? I'm a bit clueless on how to word it given my remedial knowledge of Meteor practices.

https://github.com/Semantic-Org/Semantic-UI-LESS/blob/master/README.md

**Comment by splendido** [comment]
Hi guys,
Something is moving! See [this hackpad](https://meteor.hackpad.com/Improvements-to-LESS-and-other-CSS-preprocessors-fqDPbgOH8Fn)

And @flemay come out with a [package](https://atmospherejs.com/flemay/semantic-ui) inspired by the [one](https://atmospherejs.com/nemo64/bootstrap) proposed by @Nemo64 for Bootstrap.

**Comment by flemay** [comment]
@splendido Thanks for pointing out! :)

**Comment by splendido** [comment]
:+1:

**Comment by splendido** [comment]
@jlukic, @flemay, @emgee3, @Nemo64
...I think that working together would make for a great SUI LESS package! :-)

**Comment by flemay** [comment]
@splendido  out of curiosity what is missing from my package? :)

**Comment by splendido** [comment]
@flemay, it's not the official one! ;-)

...all other SUI packages were officialy integrated by @jlukic under [Semantic-Org](https://github.com/Semantic-Org/) and published on atmosphere under the `semantic` namespace.
Whatmore they are now automatically updated through [autopublish.meteor.com](http://autopublish.meteor.com/) at every new release.

We've reserved `semantic:ui` as the package name for the official LESS version and it's still to be published...

It might be that your package is just fine to be elected as the *official* one, but it should at least migrated under some *official* umbrella :-)

**Comment by jlukic** [comment]
@flemay The only concern is on automating updates to SUI. 

I think the best place to start, if you are comforable, is giving you an official semantic-org repo where you can move your files, and then giving you access to the atmosphere organization for semantic so that you can publish the package as `semantic:ui`

After that we can discuss automating updates from the main repo. This just means updating our build script to push the `src/` to some folder in the meteor project when the main repo is updated.

**Comment by flemay** [comment]
@jlukic I am more than happy with the idea! :)

I also have automated the process of getting version X of Semantic UI and generating the files into the packages. So part of my packages has been automatically generated.

**Comment by jlukic** [comment]
I've invited you to our team on Meteor 'semantic'.

I think this is what we can do next
* Push your projects repo to [semantic-ui-meteor](https://github.com/Semantic-Org/Semantic-UI-Meteor)
* Set up autopublish on http://autopublish.meteor.com/ for the new repo
* Change semantic:ui to point to new semantic-ui-meteor repo (previously it was semantic-ui-less)
* Finally have a decent meteor less package available.

**Comment by splendido** [comment]
:+1:

**Comment by flemay** [comment]
Thanks you @jlukic!

I will also need to create a new repo for the data and a new meteor package.

**Comment by splendido** [comment]
@flemay, the repo already exists and is [semantic-ui-meteor](https://github.com/Semantic-Org/Semantic-UI-Meteor) and the package name that will be used is `semantic:ui` (... and its creation and updates will be managed by [autopublish.meteor.com](http://autopublish.meteor.com/))

**Comment by splendido** [comment]
The big part of the work, from what I can see, will be to create a grunt task to replicate the `src` folder of main SUI package inside [semantic-ui-meteor](https://github.com/Semantic-Org/Semantic-UI-Meteor) possibly renaming `.less` files to `.import.less` ones when required.
This would *replace* the need for your [flemay:semantic-ui-data](https://atmospherejs.com/flemay/semantic-ui-data) package.

Once this will be ready the code you have inside your [flemay:semantic-ui](https://atmospherejs.com/flemay/semantic-ui) package should be migrated into [semantic-ui-meteor](https://github.com/Semantic-Org/Semantic-UI-Meteor).

We'll then probably have to agree/confirm on the file names and folder structure to be used under the `client` forlder of the target app, but this won't be a big deal...

**Comment by splendido** [comment]
Other parts which should be automatically generated/updated by a grunt task could be [this one](https://github.com/flemay/meteor-semantic-ui/blob/master/data/definitions-data.js#L7-103),  [this one](https://github.com/flemay/meteor-semantic-ui/blob/master/data/sites-data.js#L7-95) and [this one](https://github.com/flemay/meteor-semantic-ui/blob/master/data/themes-data.js#L7-47)

**Comment by flemay** [comment]
@splendido I have made a gulpfile to rename/etc the files. :)

I think I don't understand how it would work without flemay:semantic-ui-data. Would you like to explain your thoughts? :)

**Comment by splendido** [comment]
...perhaps I'm missing something, but wouldn't be enough to have the src files in the same package and use the very same code you have in `flemay:semantic-ui-data` to get the asset files to copy over to the app's client structure?

**Comment by flemay** [comment]
If there was a way I would've taken this approach for sure unless I am not aware of it.

From nemo bootstrap-data:

"The reason this package exists is to provide a workaround for the limitation, that meteor does not allow static assets to be accessed in a build plugin. It is however allowed to 'use' other packages in a plugin and this other package can than provide static assets (which is what this package does)."

**Comment by splendido** [comment]
Ok, I was missing something...

**Comment by jlukic** [comment]
![](http://media.giphy.com/media/lXiRG1vwLewnehlxS/giphy.gif)
with meteor pipeline limitations

**Comment by jlukic** [comment]
So what's left to get this at `semantic:ui`?

**Comment by flemay** [comment]
I haven't moved the code yet. 

We need to create 2 repos and 2 packages.

And how to integrate with autopublish.

**Comment by jlukic** [comment]
I've added a new repo that you can push to [semantic-ui-meteor-data](https://github.com/Semantic-Org/Semantic-UI-Meteor-Data) 

Once both repos are set up I can turn on autopublishing. It works off of GitHub tagged releases.

**Comment by flemay** [comment]
Thanks @jlukic I will push today/tomorrow! :)

**Comment by flemay** [comment]
@jlukic @splendido Do you guys have preference about the package version number? Would you see semantic:ui v1.0.0 or semantic:ui v1.12.0?

**Comment by splendido** [comment]
yeah, defenitely the current SUI version to keep everything aligned!

**Comment by flemay** [comment]
I just published semantic:ui and semantic:ui-data :)

**Comment by splendido** [comment]
:+1:

**Comment by splendido** [comment]
what about the gulp tasks to update the two packages?

**Comment by splendido** [comment]
@flemay, could you make `flemay:less-autoprefixer` a dependency so that `mrt add semantic:ui` would be the only thing to run to add the package?

**Comment by flemay** [comment]
@splendido would you mind to test without `flemay:less-autoprefixer`? :)

I haven't yet open sourced. I haven't had time to look at autopublish yet.

**Comment by flemay** [comment]
If you find a way to do it without `flemay:less-autoprefixer` it would be __better__ but I haven't found a way.

**Comment by flemay** [comment]
meant to say _better_ not __better__ hehe

**Comment by splendido** [comment]
@flemay, I'll try to test it this evening (in about 12 hours...)

**Comment by flemay** [comment]
@splendido Cool thanks! What I do understand about packages is even if a package requires `less` it does not mean your application will compile `less` files automatically. You would also need to add the package if you want your application to have it.

**Comment by splendido** [comment]
well, there's a difference between having `api.use` or `api.imply` inside the `package.js` file.
`api.imply` should have the vary same effect of adding the package to the application.
...but I never tried it specifically for build plugins

**Comment by flemay** [comment]
You are right! :) Just tested it and it worked! Thanks!

**Comment by flemay** [comment]
@splendido I have updated github so if you could test locally (from the source) it would be very good and if you are happy we can then publish them on atmosphere! :)

**Comment by splendido** [comment]
I've just cloned `semantic:ui` and `semantic:ui-data` into a project's `packages` folder, I've created an empty `custom.semantic.json` and It gets filled up...

...but nothing else is happening :(
No additional files are added to my project!

Am I missing something here?

**Comment by flemay** [comment]
Maybe the README is not good enough.

Basically, the package will not generate the files straight away. It allows you to select what you want first. You will need to modify the content of custom.semantic.json (it has to be different than .custom.semantic.json).

**Comment by splendido** [comment]
I'd say a first *default* generaion would be more intuitive ;-)

**Comment by splendido** [comment]
I removed a component and it worked!
...but then I changed the theme from `default` to `github` and got this error:

```shell
client/theme.import.less:15:1: Less compiler error: 'themes//default/globals/site.variables' wasn't found. Tried -
client/themes/default/globals/site.variables,/home/luca/Tests/test-sui/client/themes/default/globals/site.variables,themes/default/globals/site.variables
```

**Comment by flemay** [comment]
would you like to open a feature request? :)

**Comment by splendido** [comment]
you mean a new issue on [Semantic-UI-Meteor](https://github.com/Semantic-Org/Semantic-UI-Meteor)?

**Comment by flemay** [comment]
yes.

And regarding your issue, maybe you need to have a look at your `theme.config.import.less`.

**Comment by flemay** [comment]
btw thanks for testing! :+1:

**Comment by splendido** [comment]
[issue opened](https://github.com/Semantic-Org/Semantic-UI-Meteor/issues/2)

...for my *bug* I'll test to change the `theme.config.import.less` accordingly...

Tnx!
