### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by larvanitis** [Semantic-Org/Semantic-UI-LESS#15]
Main repo release is at 2.2.6 for some time now but the less is not updated.

Please fix this, thanks.

**Comment by michalswietochowski** [comment]
+1

Version 2.2.7 has been already released, please update this repo & npm package.

**Comment by eXtreme** [comment]
ping @jlukic? Where is @Semantic-Pusher-Robot? 😄

**Comment by thj-dk** [comment]
Any chance of getting this updated?

**Comment by podorozhny** [comment]
ping @jlukic @Semantic-Pusher-Robot

**Comment by jlukic** [comment]
I'll get on this
