### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by stygiansabyss** [Semantic-Org/Semantic-UI-LESS#3]
While semantic-ui and semantic-ui-sass are available in bower, semantic-ui-less is not.  Would it be possible to get this added to bower?

**Comment by jlukic** [comment]
See https://github.com/Semantic-Org/Semantic-UI/issues/1926

**Comment by salarmehr** [comment]
@jlukic 
It's  possible to place the site folder out of `bower_component` folder and using a variable refer to it. Isn't it?
