### ISSUE TITLE
Make LESS 3.x compatible

### ISSUE THREAD

**Issue by kohlikohl** [Semantic-Org/Semantic-UI-LESS#30]
Tried to run this with the latest LESS 3.x (3.0.0-alpha.3) release and got following error:
```cmd
SyntaxError: variable @googleProtocol is undefined in C:\dev\teams-client-sdk\packages\semantic-ui-less\definitions\globals\site.less
on line 25, column 1:
24
25 .loadFonts();
26
```
Not yet sure why though.

Everything works fine with version `2.7.2`.

**Comment by eyal0803** [comment]
Also happens with LESS 3.0.1

**Comment by davidpanzarella** [comment]
Any update on this? Less-Loader has been recently updated to support Less 3.0, so I'd assume any updates here should now be compatible with 3.0 as well.

**Comment by rayronvictor** [comment]
Same problem in less 3.0.1

**Comment by dongcai** [comment]
Have to roll back to less '2.7.3' to make it work.

**Comment by josuevalrob** [comment]
Trying to run npm install semantic-ui -s on my angular cli project and got this: 

> /Users/josue/WebDevelop/angular/ng-book/semantic/node_modules/accord/lib/index.js:29
>       throw new Error(name + " version " + version + " is not currently supported");
>       ^
> 
> Error: less version 3.0.4 is not currently supported
>     at Object.exports.load (/Users/josue/WebDevelop/angular/ng-book/semantic/node_modules/accord/lib/index.js:29:13)
>     at Object.<anonymous> (/Users/josue/WebDevelop/angular/ng-book/semantic/node_modules/gulp-less/index.js:9:29)
>     at Module._compile (internal/modules/cjs/loader.js:678:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
>     at Module.load (internal/modules/cjs/loader.js:589:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
>     at Module.require (internal/modules/cjs/loader.js:626:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (/Users/josue/WebDevelop/angular/ng-book/semantic/node_modules/semantic-ui/tasks/watch.js:17:18)

**Comment by josuevalrob** [comment]
Sorry for the silly question, but, how can I roll back my less version?

**Comment by atti187** [comment]
`npm install less@2.7.3 --save-dev`

**Comment by josuevalrob** [comment]
Sorry, other silly question... If i run: 
`npm install --global less@2.7.3 --save-dev`
It shows me: 
> /Users/josue/.npm-packages/bin/lessc -> /Users/josue/.npm-packages/lib/node_modules/less/bin/lessc
> + less@2.7.3
> updated 1 package in 2.756s

Now, But If after that, I go inside the Angular project, and try
`npm install semantic-ui`
I got the same error: 

> Error: less version 3.0.4 is not currently supported
>     at Object.exports.load (/Users/josue/WebDevelop/angular/ng-book/semantic/node_modules/accord/lib/index.js:29:13)
>     at Object.<anonymous> (/Users/josue/WebDevelop/angular/ng-book/semantic/node_modules/gulp-less/index.js:9:29)
>     at Module._compile (internal/modules/cjs/loader.js:678:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
>     at Module.load (internal/modules/cjs/loader.js:589:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
>     at Module.require (internal/modules/cjs/loader.js:626:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (/Users/josue/WebDevelop/angular/ng-book/semantic/node_modules/semantic-ui/tasks/watch.js:17:18)

The only way to make it work is running `npm install less@2.7.3 --save-dev` and getting this: 

> + less@2.7.3
> added 18 packages from 22 contributors, removed 6 packages, updated 1 package and moved 1 package in 27.923s

And now, I can start a semantic project by `npm install semantic-ui`

**Is there any way to reinstall less@2.7.3 globally?**

**Comment by 0paIescent** [comment]
Does anyone feel that the four vulnerabilities found by `npm audit` are any danger?

**Comment by 0paIescent** [comment]
@josuevalrob I'm pretty sure that what you'd need to do is just `npm uninstall -g less`, then reinstall with the correct version `npm install -g less@2.7.3`.

**Comment by dragondraico** [comment]
I had the same problem as everyone, the solution I found was to install cjs and accord, then install semantic-ui and this time if it was allowed to install correctly

**Comment by Vages** [comment]
Great, @sciyoshi! 

Just to make it darned clear to anyone: 

`@import "~semantic-ui-less/theme.less";` -> `@import (multiple) "~semantic-ui-less/theme.less";`

**Comment by Vages** [comment]
Time to close this now, @kohlikol

**Comment by Serhansolo** [comment]
Guys, I am not sure but I am still getting an error my less version is apparently 3.x+ :)


`Error: less version 3.5.2 is not currently supported
    at Object.exports.load (/Users/suy20680/Documents/Projects/test-semantic/test-app/node_modules/accord/lib/index.js:29:13)
    at Object.<anonymous> (/Users/suy20680/Documents/Projects/test-semantic/test-app/node_modules/gulp-less/index.js:9:29)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/suy20680/Documents/Projects/test-semantic/test-app/node_modules/semantic-ui/tasks/watch.js:17:18)
`

**Comment by Vages** [comment]
Remembered to change the import, @Serhansolo ?

**Comment by ThanosSiopoudis** [comment]
Looks like less 3.5.x has some breaking changes. 3.0.x works after this merge, but not 3.5.x
The problem is that in Less 3.5.x inline '@' expressions are no longer math'd (https://github.com/less/less.js/issues/3265#issuecomment-402804254)

See error output below with Semantic-UI-Less 2.3.3 and less 3.5.3:
```@ribbonMargin: 1rem;
@ribbonOffset: ~"calc("-@ribbonMargin~" - "@ribbonTriangleSize~")";
^
Operation on an invalid type
      in /Users/[...]/node_modules/semantic-ui-less/themes/default/elements/label.variables (line 133, column 0)
```

**Comment by ThanosSiopoudis** [comment]
@JonRowe did you add `(multiple)` to your `@import` statement in theme.config? 2.3.3 and 3.0.4 works fine for me

**Comment by JonRowe** [comment]
Ah my bad, totally didn't, yep 3.0.4 works, just 3.5 and 3.6 don't now.

**Comment by Serhansolo** [comment]
@Vages, sorry for the delayed reply. I just solved the isseu by downgrading my less for the project to 2.7.3 😏

**Comment by ahbapAldirmaz** [comment]
compatibility new less;
example
filename : label.variables

change 133.line 

//@ribbonOffset: ~"calc("-@ribbonMargin~" - "@ribbonTriangleSize~")";
@ribbonOffset: e("calc(-@{ribbonMargin} - @{ribbonTriangleSize})");

**Comment by jlukic** [comment]
This will be fixed in patch today with https://github.com/Semantic-Org/Semantic-UI/pull/6512
