### ISSUE TITLE
flags.png is missing from the material theme

### ISSUE THREAD

**Issue by revik** [Semantic-Org/Semantic-UI-LESS#31]
when trying to set the theme as material in theme.config, I get

`Module not found: Error: Can't resolve './themes/material/assets/images/flags.png' in /node_modules/semantic-ui-less`

way to reproduce - jus change set the theme in theme.config as material instead of default for all components.

solution - copying the images folder from the default theme to material solves the issue.

**Comment by revik** [comment]
Instead of the above I just left the flag in theme.config set to default instead of material.
my bad...

**Comment by Rex90** [comment]
were you using create-react-app with this by any chance?  if so, how were your folders structured? 
thanks

**Comment by chaadow** [comment]
For me it was the `images` directory present in `.yarnclean` so I had to remove it. ( for anyone still experiencing this issue)
