### ISSUE TITLE
Module Build Failed: Missing closing ')'

### ISSUE THREAD

**Issue by theshapguy** [Semantic-Org/Semantic-UI-LESS#38]
When I import semantic-ui-less in my Vue Project, everything is setup. Getting this error.
```bash
Module build failed:


;(function ($, window, document, undefined) {
                                          ^
Missing closing ')'
      in /Users/Developer/ui/node_modules/semantic-ui-less/definitions/modules/transition.js (line 11, column 44)
```

**Comment by hanshenrik** [comment]
Experienced the same. Appeared after upgrading of `less` dependency from `v3.0.0-alpha.3` to `v3.0.1`. Perhaps some syntax errors present here that are no longer allowed?

`semantic-ui-less@v2.2.14` with `less@v3.0.0-alpha.3` works fine
`semantic-ui-less@v2.2.14` with `less@v3.0.1` *produce this error*

**Comment by theshapguy** [comment]
Same here, I just checked with less@2.7.3 and it worked. I'll try to see if I can create a fix over this weekend.

**Comment by Gitii** [comment]
I have the same issue.
It seems that in my case, less tries to load *.js-files instead of *.less-files (?!):
-> semantic.less imports all files without extension.
After adding the extensions, it worked.

**Comment by honzajerabek** [comment]
same here

**Comment by SVAR7BERG** [comment]
Same here. Still nothing happened? Is there a solution?

**Comment by codev0** [comment]
same here
```js
"less": "^3.0.1",
"semantic-ui-less": "^2.3.1",
```

**Comment by Vages** [comment]
It has been fixed now: https://github.com/Semantic-Org/Semantic-UI-LESS/issues/30#issuecomment-395296758 As said in that comment, you have to make imports of `theme.config` multiple imports: `@import "~semantic-ui-less/theme.less";` -> `@import (multiple) "~semantic-ui-less/theme.less";`

For the record: I'm on `"semantic-ui-less": "2.3.2"` now, with `"less": "3.0.4"`.

**Comment by Vages** [comment]
Time to close this now, @theshapguy?

**Comment by Vages** [comment]
Note that you may experience new, unrelated problems by upgrading to 3.5.x: https://github.com/Semantic-Org/Semantic-UI-LESS/issues/46
