### ISSUE TITLE
Cannot create property '_index' on string '!important': after upgrading less@3.9.0 to @3.10.x

### ISSUE THREAD

**Issue by drdmitry** [Semantic-Org/Semantic-UI-LESS#68]
After upgrading less@3.9.0 module to less@3.10.0 or less@3.10.1 I am getting the following error during the webpack build.
Rolling back to less@3.9.0 helps.

> ERROR in ./node_modules/semantic-ui-less/semantic.less (./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js!./node_modules/semantic-ui-less/semantic.less)
> Module build failed (from ./node_modules/less-loader/dist/cjs.js):
> 
> 
> /*******************************
> ^
> Cannot create property '_index' on string '!important'
>       in \node_modules\semantic-ui-less\themes\default\collections\table.variables (line 1, column -1)
>  @ ./node_modules/semantic-ui-less/semantic.less 1:14-95

Versions:
    "css-loader": "^3.2.0",
    "less-loader": "^5.0.0",
    "semantic-ui-less": "^2.4.1",
    "webpack": "^4.39.2",
    "webpack-cli": "^3.3.7",
    "webpack-dev-server": "^3.8.0"

**Comment by OwenPattison** [comment]
Getting the same issue here.

**Comment by SunnyDark** [comment]
Same here...
Anyone figured out what is causing the issue?

**Comment by drdmitry** [comment]
now it works with less@3.10.3
